### ISSUE TITLE
Add testing framework for react components in deposit module

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#109]

**Comment by dismorfo** [comment]
Done using [Jest test framework](https://jestjs.io/), same configuration as [react-invenio-deposit](https://github.com/inveniosoftware/react-invenio-deposit). See [react-ultraviolet-deposit](https://github.com/dismorfo/react-ultraviolet-deposit).

**Comment by dismorfo** [comment]
I was hoping to add more tests, including calling the suggestion API but I don't see any example of testing components that use RemoteSelectField.js in [react-invenio-deposit](https://github.com/inveniosoftware/react-invenio-deposit/tree/master/src/lib/components) or [ react-invenio-forms](https://github.com/inveniosoftware/react-invenio-forms).
