### ISSUE TITLE
Setup metadata repository for local records which represent real use cases

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#12]
To get started, we need to migrate the metadata records that represent the conceptual use cases for collection needs into UltraViolet. We will begin by retrieving them from the read-only `invenio-nyu-openshift` repo from the Fall 2020 at [https://github.com/nyudlts/invenio-nyu-openshift](https://github.com/nyudlts/invenio-nyu-openshift) and bring them into the `ultraviolet-metadata` repository.

My approach is the following:

- bring the records over as they are
- rename them to represent our existing use cases as represented [here](https://docs.google.com/spreadsheets/d/1dEXI7u6_sdkxVqpL__DO2l8TLgCmqpYbeHocdRXFfGk/edit?usp=sharing)
- convert them into the schema required by UltraViolet
- re-name them according to the IDs generated by the system

**Comment by ekate** [comment]
The repo has been created
