### ISSUE TITLE
Add option to launch fixtures with Invenio-CLI for local deployment

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#19]
https://github.com/inveniosoftware/invenio-app-rdm/issues/668

**Comment by andrewbattista** [comment]
Possible steps include the following:
- [ ] create directory space for sample records, taken from the use cases at https://github.com/NYU-DataServices/ultraviolet-metadata/tree/main/metadata
- [ ] adopt the logic of invenio-cli to execute a bash script that looks for records and indexes them upon local startup of UV. See https://inveniordm.docs.cern.ch/reference/cli/#shell-completion
- [ ] Submit this to the upstream project
- [ ] Put in our sample records into the UV codebase
