### ISSUE TITLE
Expand the Range of Elements Prominent in the Items Show Pages and Deposit Form

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#31]
The "out of the box" UltraViolet only displays some but not all of the elements in a metadata record in the deposit form and item show page. We want to override the Invenio theme we are using so that more elements are prominent, and we need to configure the deposit form to enable the addition of more elements.

**Comment by ekate** [comment]
@andrewbattista I think I can pass additional required fields list and @dismorfo can update  the form to use them. However it won't affect REST API and uses will still be able to submit records without required fields through REST API. To overcome that we will have to disallow user's direct access to entry points which create records. Instead we will have additional entry point which will accept REST calls from users, check the record and then send a record creation call. 
I have a question though - how necessary is that feature ? Why do we want additional required fields and what they should be ?
