### ISSUE TITLE
Develop Prominent Version Number on UltraViolet app

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#33]
It would be nice to have a space on the homepage UI that recognizes which version of UltraViolet we are running and prints it. This feature would help local development. Possibly this enhancement could take place via a spot on the `config.yml` file

**Comment by lhenze** [comment]
This would also be helpful for usability testing!

**Comment by lhenze** [comment]
When I commented, I was thinking of the Invenio RDM version number.  Both that, and an internal UV release number, would be helpful.  I propose they appear in the universal footer, so  it's always clear, even across different instances, where we are in the cycle(s).

**Comment by andrewbattista** [comment]
I agree. Is it possible to just have the UV release number align with the InvenioRDM number? And I agree it should be in the footer. It looks like Zenodo handles this by adding a `version.py` file within the modules directory [like so](https://github.com/zenodo/zenodo/blob/master/zenodo/version.py)

Either way, this would be a great feature for us to incorporate

**Comment by mnyrop** [comment]
duplicate of #68, closed in #93 
(can open new ticket if it is also desirable to show InvenioRDM version in footer.)
