### ISSUE TITLE
Document customization workflow

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#35]
As we continue to gain momentum on development, we need a more broadly documented approach to staging and submitting look and feel changes. Ideally, this documentation can live on the UltraViolet project documentation wiki, and it can model some basic processes for overriding the default InvenioRDM themes

**Comment by andrewbattista** [comment]
I am happy to pair up on this to help get something off the ground

**Comment by ekate** [comment]
@lhenze do you think you will have time to work on that ?

**Comment by lhenze** [comment]
@ekate Yes, I should be able to work on that, once the dev environment setup is stable.

**Comment by andrewbattista** [comment]
Adding a note for @mnyrop to add in some instructions here about using assets-watch to make look feel modifications more efficient
