### ISSUE TITLE
Establish an overarching approach for and design concept for "Communities"

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#36]
UltraViolet has a concept of Communities that can be used to link like records together. These can be deployed in a number of ways, including:
- individual items within a collection
- major subsections of the catalog (held/licensed data as opposed to researcher submissions)
- metadata only records from external discovery projects

Each of these communities needs (or benefits) from a logo and a brief description. We should create these to model our approach. The work steps include:
- Documenting how to assign individual records to a community
- uploading logos
- Writing an internal policy statement to guide our project

**Comment by kwissel** [comment]
Got it.  Glad to know there is a communities functionality we can leverage to indicate these groups.

**Comment by andrewbattista** [comment]
There is, but it's not well documented. I'm still looking to decipher whether communities are comprised of individual users (and thus all of their items are in a community) or if we can make groupings of items in a community. Also, it remains to be seen whether or not we should allow individual users to create communities or not.

**Comment by ekate** [comment]
@andrewbattista, @kwissel  communities are not yet fully functional, e.g. you can not assign record or user to a community. They will be included in June release

**Comment by ekate** [comment]
I will close this for now. We can re-open it when communities are fully implemented.
