### ISSUE TITLE
Draw up internal policy for curating images and make UI adjustments

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#39]
When users upload a large (in size) image it doesn't render. We need to establish a few things related to internal curation policy, documentation, and messaging within the app. This could mean

- Improve the default message of `Sorry, we are unfortunately not able to preview this file.` with something more elegent

- Document a workflow for reducing image sizes as surrogates for preview only

- Investigating some other solution that lets depositors know about the limits of image size for preview

**Comment by ekate** [comment]
This is a bug not feature and it will be fixed shortly.
