### ISSUE TITLE
Customize Access Information to account for Proprietary Data

### ISSUE THREAD

**Issue by andrewbattista** [nyudlts/ultraviolet#46]
This may not be possible, but we are looking for a more refined way to disambiguate between restricted files that are restricted because of PII or depositor demands, and files that are restricted because they are licensed to NYU users only. 

One approach is to expand the range of values allowed in [Access Information](https://inveniordm.docs.cern.ch/reference/metadata/#access-information) but we don't know if this can be done

Another is to signpost by coming up with a custom `resource_type` and badge that says something like "licensed resource" and then restrict access to the data via another means (like at the storage layer)

**Comment by andrewbattista** [comment]
This is directly related to issue #112 - we can add "licensed resource to the localized vocabulary we are using for `resource_type`

**Comment by dismorfo** [comment]
Hi @andrewbattista, I see this is assigned to me. Can you tell me more about this issue? I'm not sure  what I need to do.

**Comment by andrewbattista** [comment]
@dismorfo sure! The ability to add a localized list is within app data. See this file for the resource type .yaml file: https://github.com/nyudlts/ultraviolet/blob/main/app_data/vocabularies/resource_types_nyu.yaml

Ostensibly, this is a three part task 

- Adding a new resource type called "licensed resource" or something like that. 
- Partnering with either me or @kwissel to make sure the details in the yaml file match up and are OK
- indexing a test record that is licensed data and making sure that the label on the search results appears okay.

Does that help get things started? I imagine this task as being started / staged and then commented on during a standup next week.

**Comment by debverhoff** [comment]
Stale request. UV metadata, including the access information, is defined in a scheme that is maintained by KARMS.
