### ISSUE TITLE
Insert link to https://guides.nyu.edu/ultraviolet and potentially other relevant links on the application footer

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#52]
This issue is a multi-step process

- make sure that the patron-facing policies and information we have [drafted in this doc](https://docs.google.com/document/d/1aWwpG4rznkt0IMqyfP9RpTw4OoDVJzvah_2Ugd3OjAE/edit?usp=sharing) are placed within the UltraViolet LibGuide at https://guides.nyu.edu/ultraviolet
- Decide whether to link to this in the footer or somewhere else in the application
- Override the theme or config file so the link is prominent

**Comment by mnyrop** [comment]
@andrewbattista i'll try this one and then ask you to review!
