### ISSUE TITLE
Generate and install NYU-specific favicon for UltraViolet

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#53]

**Comment by lhenze** [comment]
Hi, I just created a PR for this: https://github.com/nyudlts/ultraviolet/pull/73

Ultimately I'd like to use another way to point to icons so it will look cleaner - 
https://wp.nyu.edu/torchtech/
versus
https://www.nyu.edu/

But this one should be ok for now.  (It's the one used on NYU home page.)
