### ISSUE TITLE
Simple template changes: Add “Browse repository content” button 

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#56]
InvenioRDM user can list all records  by pressing magnifying glass icon next to the search box in the[ page header](https://inveniordm.web.cern.ch/search?q=&l=list&p=1&s=10&sort=newest). 
During UI testing users confirmed that it is a  useful feature but most did not expect that they can render repository content by pressing on the magnifying glass icon. We want to add a link in the header labeled  "List all records" with the same functionality. 

InvenioRDM frontpage is generated using [djinja template](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html). That template could be overwritten for the local  instance. We already have [our version](https://github.com/nyudlts/ultraviolet/blob/main/templates/semantic-ui/invenio_app_rdm/frontpage.html) which can be further modified. We also will need to overwrite [header templates](https://github.com/inveniosoftware/invenio-app-rdm/tree/master/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm)

**Comment by Sinclert** [comment]
Hi @ekate 👋🏻 

Could you provide a bit of context? Please consider I have been thrown into this sprint without much context of previous discussions.

- Which HTML template do you want to be updated? (a link would help)
- Where do you want the button to be? upper-left corner? upper-right corner? ...
- Is it supposed to show _repository content_ at this stage?

**Comment by ekate** [comment]
@lhenze could you please provide some clarification on the design aspect. (I assume that it should be a link next to "Uploads" link)

**Comment by Sinclert** [comment]
> InvenioRDM user can list all records by pressing magnifying glass icon next to the search box in the[ page header](https://inveniordm.web.cern.ch/search?q=&l=list&p=1&s=10&sort=newest).
> During UI testing users confirmed that it is a useful feature but most did not expect that they can render repository content by pressing on the magnifying glass icon. We want to add a link in the header labeled "List all records" with the same functionality.

Ok, so my understanding is that the button, which would **substitute** the magnifying glass 🔍 , would say _"List all records"_ and not _"Browse repository content"_ as stated in the issue title. **Is that right?**

**Comment by lhenze** [comment]
Hi, What I'm thinking - 
The search function (and the functionality of the magnifying glass) remain untouched. 
For the actual language on the label of the link – I vote for a simple "Browse all"

As for implementation, specific template, etc, I'm not yet sure how to do this. Perhaps we can discuss?

**Comment by Sinclert** [comment]
After a bit of research, it seems that the _proper way_ of extending the header menu (to include the new _Browse all_ button), would need a Python function registering, as show in [the documentation](https://invenio-theme.readthedocs.io/en/latest/usage.html#menus):

```python
from flask_menu import register_menu

@app.route('/search')
@register_menu(app, 'main.browse', 'Browse all', order=1)
def browse_all_menu():
    return ""
```

**Comment by ekate** [comment]
In the InvenioRDM context ( which is different from Invenio Framework context) the _proper_ way to do it will be to overwrite the header_frontpage.html
