### ISSUE TITLE
Simple template changes: Date in blue --- label -- should be prepended by “originally published”

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#58]

**Comment by mnyrop** [comment]
@lhenze can you provide a description / screenshot for this one too? thanks!

**Comment by lhenze** [comment]
@mnyrop  it's actually the same screenshot -- Except it says "First published" -- Just asked in slack channel about exact language

**Comment by debverhoff** [comment]
I don't see date in blue. This seems stale from an older version of I-RDM.
