### ISSUE TITLE
Simple template changes: Version and publication date

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#68]
Local adopters and users have expressed the desire to see the app version number prominent on the footer. Now that we know how to override the theme to make customizations on the footer, it seems like all we need is to find a way to insert a version number (possibly in the `invenio.cfg` file, and then have the application grab that. Can we implement this even while we have a rudimentary convention for internal semantic versioning of UltraViolet 💜

**Comment by mnyrop** [comment]
closed via #93
